import jsPDF from "jspdf";

export function exportFarmReport(report) {
  const doc = new jsPDF();

  const today = new Date().toLocaleDateString();

  doc.setFontSize(22);
  doc.text("FarmHand PRO", 20, 20);

  doc.setFontSize(16);
  doc.text("Farm Report", 20, 30);

  doc.setFontSize(10);
  doc.text(`Generated: ${today}`, 20, 38);

  doc.line(20, 42, 190, 42);

  doc.setFontSize(14);
  doc.text("Farm Summary", 20, 55);

  doc.setFontSize(11);

  doc.text(
    `Total Animals: ${report.totalAnimals}`,
    25,
    68
  );

  doc.text(
    `Total Income: R ${Number(
      report.totalIncome
    ).toLocaleString(undefined, {
      minimumFractionDigits: 2,
    })}`,
    25,
    78
  );

  doc.text(
    `Total Expenses: R ${Number(
      report.totalExpenses
    ).toLocaleString(undefined, {
      minimumFractionDigits: 2,
    })}`,
    25,
    88
  );

  doc.text(
    `Net Profit: R ${Number(
      report.netProfit
    ).toLocaleString(undefined, {
      minimumFractionDigits: 2,
    })}`,
    25,
    98
  );

  doc.setFontSize(14);
  doc.text("Livestock", 20, 118);

  doc.setFontSize(11);

  doc.text(
    `Animals Registered: ${report.animals.length}`,
    25,
    130
  );

  doc.setFontSize(14);
  doc.text("Breeding", 20, 148);

  doc.setFontSize(11);

  doc.text(
    `Breeding Records: ${report.breeding.length}`,
    25,
    160
  );

  doc.setFontSize(14);
  doc.text("Animal Health", 20, 178);

  doc.setFontSize(11);

  doc.text(
    `Health Records: ${report.health.length}`,
    25,
    190
  );

  doc.setFontSize(10);

  doc.text(
    "Generated by FarmHand PRO",
    20,
    280
  );

  doc.save("FarmHand-Pro-Report.pdf");
}
